### ISSUE TITLE
What kind of project allows fudders in the name of free speech!?

### ISSUE THREAD

**Issue by Marooo743** [sunflower-farmers/sunflower-farmers#102]
I really got frustrated by negative speach about this project in discord, fudders are banned in successful communities, why are we allowing it ?! And the mod intervals.eth are muting me for addressing this critical issue, we are not a country to have free speech we are a closed community and we have made alot of enemies, competition, I feel like we're infiltrated by other game investors gaining a lot of momentum does this effect, we need a solution fast or negativety will brevail and say goodbye to the community, 
![Screenshot_20220106-104952_Discord](https://user-images.githubusercontent.com/93843459/148357174-44820708-a507-48d4-8838-7732f6c112b6.jpg)

**Comment by JeromeRadlach** [comment]
i dont think this is an issue related to the codebase. can you please remove this issue so we can continue working on the project.

**Comment by Marooo743** [comment]
You could be among us also, why should we trust you ?!

**Comment by adamhannigan** [comment]
@Marooo743 Sorry you had a poor experience.

Right now we have entrusted a few community members to help with the moderation of the Discord server. We have no funding and no team except the community to help us achieve anything.

I'm hoping the current mods can make the decision that will benefit the community. As mentioned above, this conversation is probably best had in the Discord channel

**Comment by Marooo743** [comment]
It's an infltration problem, guys you thought coming to help actually fudding 
![Uploading Screenshot_20220106-215651_Discord.jpg…]()
