### ISSUE TITLE
Use $SFF when token referencing the token

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-farmers/sunflower-farmers#43]
There are a few places in the documentation and the gameplay where it is not clear that the `$` is referring to SFF.

**Includes**

- Find all the locations where we are referencing the Sunflower Farmer Token and include the symbol and the logo if possible.

**ProjectJourneyMan - Discord**

```
Please update the site to correctly use the $ symbol.
10 SFF -> ten Sunflower tokens
10 $SFF -> ten Sunflower tokens
$10 -> ten USD
$10 SFF -> ten USD worth of SFF
```

**Comment by Rofrtd** [comment]
Done

**Comment by Rofrtd** [comment]
Done at the gameplay. Still documentation to do

**Comment by Swastyy** [comment]
Hi @adamhannigan @Rofrtd Can I do this?

**Comment by adamhannigan** [comment]
@Swastyy Hi there, this has been completed in the game. I will close for now.

We just have the admin task of updating our docs
