### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-farmers/sunflower-farmers#84]
### Issue:
- **NO License is Specified** 😟
- **Missing License file** (`LICENSE`)
   > stating appropriate License name and copyright authors

I was exploring the repo (obviously because of recent hype of Sunflower Farmers👍) and found out that the repo (at least main branch) has not specified any License (or License file).

### Possible Solution: 😊
I believe that, adding an _appropriate License_ would make sure that the code is used and implemented correctly. Apparently avoiding any improper/(unauthorized) uses.

**Comment by adamhannigan** [comment]
Thanks @Pranav-yadav 

Good spot, I will add it now.
