### ISSUE TITLE
Description Meta Tag is Missing

### ISSUE THREAD

**Issue by Pranav-yadav** [sunflower-farmers/sunflower-farmers#86]
### Issue:
- Description Meta Tag ( `<meta name="description" content="">` ) is missing from `public/index.html` file

### Possible Solution: 😊
- Add _description meta tag_ with an appropriate description to _content_ attribute
  e.g. 
  `<meta name="description" content="Play to Earn Crypto Farming Game.">`

PS: I would be happy to work on it :)

**Comment by adamhannigan** [comment]
@Pranav-yadav We love to see you join as a contributor. Do you want to open a PR for this?

**Comment by Pranav-yadav** [comment]
> @Pranav-yadav We love to see you join as a contributor. Do you want to open a PR for this?
 Yup.
