### ISSUE TITLE
Gas price is hardcoded

### ISSUE THREAD

**Issue by EibrielInv** [sunflower-farmers/sunflower-farmers#88]
Please get current gas price from an oracle and set it accordingly.

Harcoding the gas to 500 Gwei, since the game is so popullar, only rises the minimum gas to 500 Gwei without any benefit to the players.

A free endpoint to get gas prices is: https://gpoly.blockscan.com/gasapi.ashx?apikey=key&method=gasoracle

**Comment by adamhannigan** [comment]
@EibrielInv We are currently using Web3 estimateGas functionality to retrieve this price.

The issue is that the network is heavily congested and that is the actual gas price that is needed.
